[client]
showErrorDetails = false
showWarningOnDirectExecution = false
toolbarMode = "minimal"

[logger]
level = "error"

[server]
headless = true
runOnSave = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
